DROP DATABASE IF EXISTS zljr4eqwwsxhhvay;
CREATE DATABASE zljr4eqwwsxhhvay;
USE zljr4eqwwsxhhvay;
/*CREATE MAJOR TABLE */
CREATE TABLE Major (
	MajorID INT(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(300) NOT NULL,
    requirements VARCHAR(200) NOT NULL
);
/*INSERT MAJORS */
INSERT INTO Major
VALUES ('1', 'Accounting (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5149'),
('2', 'Aerospace Engineering (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5541'),
('3', 'American Studies and Ethnicity (African American Studies)(BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5190'),
('4', 'American Studies and Ethnicity (Asian American Studies)(BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5191'),
('5', 'American Studies and Ethnicity (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5189'),
('6','American Studies and Ethnicity (Chicano/Latino Studies) (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5192'),
('7', 'Animation and Digital Arts (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5155'),
('8', 'Anthropology (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5197'),
('9', 'Anthropology (Visual Anthropology) (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5198'),
('10','Applied and Computational Mathematics (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5355'),
('11', 'Applied and Computational Mathematics (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5356'),
('12', 'Applied Mechanics (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5580'),
('13', 'Architectural Studies (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5051'),
('14', 'Architecture (BArch)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5082'),
('15','Art (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5066'),
('16','Art History (BA)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5208'),
('17','Arts, Technology and the Business of Innovation (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5081'),
('18','Astronautical Engineering (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5551'),
('19','Astronomy (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5390'),
('20','Astronomy (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5387'),
('21', 'Biochemistry (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5219'),
('22', 'Biological Sciences (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5215'),
('23', 'Biological Sciences (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5216'),
('24', 'Biomedical Engineering (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5555'),
('25','Biomedical Engineering, Biochemical Engineering Emphasis, (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5556'),
('26', 'Biomedical Engineering, Electrical Engineering Emphasis, (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5557'),
('27', 'Biomedical Engineering, Mechanical Engineering Emphasis, (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5558'),
('28', 'Biophysics (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5391'),
('29','Business Administration (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5086'),
('30', 'Business Administration (Cinematic Arts) (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5087'),
('31', 'Business Administration (International Relations) (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5088'),
('32', 'Business Administration (Real Estate Finance) (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5089'),
('33', 'Business Administration (World Program) (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5090'),
('34','Central European Studies (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5426'),
('35','Chemical Engineering (BS)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5564'),
('36','Chemical Engineering, Biochemical Engineering Emphasis, (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5565'),
('37','Chemical Engineering, Environmental Engineering Emphasis, (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5566'),
('38','Chemical Engineering, Nanotechnology Emphasis, (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5567'),
('39','Chemical Engineering, Petroleum Engineering Emphasis, (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5568'),
('40','Chemical Engineering, Polymer/Materials Science Emphasis, (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5569'),
('41', 'Chemical Engineering, Sustainable Energy Emphasis (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6109'),
('42', 'Chemistry (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5236'),
('43', 'Chemistry (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5232'),
('44', 'Chemistry (Chemical Biology) (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5235'),
('45','Chemistry (Chemical Nanoscience) (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5234'),
('46','Chemistry (Research) (BS)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5233'),
('47','Choral Music (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5755'),
('48','Cinema and Media Studies (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6079'),
('49','Cinematic Arts, Film and Television Production (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5160'),
('50','Cinematic Arts, Film and Television Production (BFA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5161'),
('51', 'Civil Engineering (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6110'),
('52', 'Civil Engineering, Building Science Emphasis (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6111'),
('53', 'Civil Engineering, Environmental Engineering Emphasis (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6112'),
('54', 'Civil Engineering, Structural Engineering Emphasis (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6113'),
('55','Classics (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5242'),
('56', 'Cognitive Science (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5411'),
('57', 'Communication (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5449'),
('58', 'Comparative Literature (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5246'),
('59','Composition (BM)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5741'),
('60', 'Computational Neuroscience (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5372'),
('61', 'Computer Engineering and Computer Science (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5594'),
('62', 'Computer Science (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5597'),
('63', 'Computer Science (Games) (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5598'),
('64','Computer Science/Business Administration (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5599'),
('65','Contemporary Latino and Latin American Studies (BA)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6104'),
('66','Dance (BFA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5480'),
('67','Dental Hygiene (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5483'),
('68','Earth Sciences (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5257'),
('69','East Asian Area Studies (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5263'),
('70','East Asian Languages and Cultures (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5269'),
('71', 'Economics (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5274'),
('72', 'Economics/Mathematics (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5277'),
('73', 'Electrical Engineering (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5614'),
('74', 'English (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5286'),
('75','Environmental Engineering (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6114'),
('76','Environmental Science and Health (BA)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5303'),
('77','Environmental Science and Health (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5304'),
('78','Environmental Studies, Climate, Earth and Environment Concentration (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5297'),
('79','Environmental Studies, Climate, Earth and Environment Concentration (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5301'),
('80','Environmental Studies, Environmental Public Policy Concentration (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5298'),
('81', 'Environmental Studies, Environmental Public Policy Concentration (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5302'),
('82', 'Environmental Studies, Oceans, Life and People Concentration (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5296'),
('83', 'Environmental Studies, Oceans, Life and People Concentration (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5300'),
('84', 'Environmental Studies, Sustainability, Energy and Society Concentration (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5295'),
('85','Environmental Studies, Sustainability, Energy and Society Concentration (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5299'),
('86', 'Fine Arts (BFA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5065'),
('87', 'French (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5308'),
('88', 'Gender Studies (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5312'),
('89','GeoDesign (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5441'),
('90', 'Geological Sciences (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5256'),
('91', 'Global Health Studies (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5722'),
('92', 'Global Studies (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5199'),
('93', 'Health and Humanity (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5317'),
('94','Health and the Human Sciences (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5326'),
('95','Health Promotion and Disease Prevention Studies (BS)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5721'),
('96','History (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5318'),
('97','History and Social Science Education (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5319'),
('98','Human Biology (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5218'),
('99','Human Biology (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5217'),
('100','Human Development and Aging (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5654'),
('101', 'Human Development and Aging, Health Science Track, (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5655'),
('102', 'Human Development and Aging, Honors Programs, (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5656'),
('103', 'Industrial and Systems Engineering (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5625'),
('104', 'Interactive Entertainment (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5163'),
('105','Interdisciplinary Archaeology (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5421'),
('106','International Relations (BA)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5329'),
('107','International Relations (Global Business) (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5330'),
('108','International Relations and the Global Economy (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5331'),
('109','Italian (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5310'),
('110','Jazz Studies (BM)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5742'),
('111', 'Jewish Studies (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6105'),
('112', 'Journalism (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6126'),
('113', 'Judaic Studies Emphasis (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5420'),
('114', 'Law, History, and Culture (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5320'),
('115','Lifespan Health (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5657'),
('116', 'Linguistics (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5343'),
('117', 'Linguistics and Cognitive Science (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6080'),
('118', 'Linguistics and East Asian Languages and Cultures (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5345'),
('119','Linguistics and Philosophy (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5344'),
('120', 'Linguistics and Psychology (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5410'),
('121', 'Mathematics (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5353'),
('122', 'Mathematics (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5354'),
('123', 'Mathematics/Economics (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5359'),
('124','Mechanical Engineering (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5545'),
('125','Mechanical Engineering, Petroleum Engineering, (BS)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5546'),
('126','Media Arts and Practice (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5167'),
('127','Middle East Studies (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5367'),
('128','Music (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5754'),
('129','Music Industry (BM)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5752'),
('130','Music Industry (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5753'),
('131', 'Music Production (BM)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5743'),
('132', 'Narrative Studies (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5288'),
('133', 'Neuroscience (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5370'),
('134', 'Neuroscience (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5371'),
('135','Non-Governmental Organizations and Social Change (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5431'),
('136','Occupational Therapy (BS)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5678'),
('137','Performance (Classical Guitar) (BM)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5745'),
('138','Performance (Flute), (Oboe), (Clarinet), (Bassoon), (Saxophone), (French Horn), (Trumpet), (Trombone), (Tuba) or (Percussion) (BM)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5750'),
('139','Performance (Organ) (BM)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5747'),
('140','Performance (Piano) (BM)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5746'),
('141', 'Performance (Popular Music) (BM)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5751'),
('142', 'Performance (Studio Guitar) (BM)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5744'),
('143', 'Performance (Violin), (Viola), (Violoncello), (Double Bass) or (Harp) (BM)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5748'),
('144', 'Performance (Vocal Arts) (BM)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5749'),
('145','Philosophy (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5376'),
('146', 'Philosophy, Politics and Law (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5377'),
('147', 'Physical Sciences (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5392'),
('148', 'Physical Sciences (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5258'),
('149','Physics (BA)', 'http://catalogue.usc.edu/content.php?catoid=6&navoid=1553'),
('150', 'Physics (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5386'),
('151', 'Physics/Computer Science (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5388'),
('152', 'Political Economy (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5275'),
('153', 'Political Science (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5399'),
('154','Psychology (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5408'),
('155','Public Policy (BS)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6072'),
('156','Public Relations (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5472'),
('157','Real Estate Development (BS)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5822'),
('158','Religion (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5419'),
('159','Russian (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5425'),
('160','Social Sciences, with an Emphasis in Economics (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5276'),
('161', 'Social Sciences, with an Emphasis in Psychology (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5409'),
('162', 'Sociology (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5430'),
('163', 'Spanish (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5438'),
('164', 'Theatre (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5504'),
('165','Theatre, Acting Emphasis, (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5505'),
('166','Theatre, Acting Emphasis, (BFA)' , 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5507'),
('167','Theatre, Design Emphasis, (BA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5506'),
('168','Theatre, Design Emphasis, (BFA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5508'),
('169','Theatre, Sound Design Emphasis, (BFA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5509'),
('170','Theatre, Stage Management Emphasis, (BFA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5510'),
('171', 'Theatre, Technical Direction Emphasis, (BFA)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5511'),
('172', 'Urban Studies and Planning (BS)', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6073'),
('173', 'Visual and Performing Arts Studies (BA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5512'),
('174', 'Writing for Screen and Television (BFA)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5172'),
('175', 'Food Industry Management Program', 'http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5091');

/*CREATE MINOR TABLE */
CREATE TABLE Minor (
	MinorID INT(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    requirements VARCHAR(200) NOT NULL
);
/*INSERT MINORS - MARK*/
INSERT INTO Minor 
VALUES ('1','2-D Art for Games Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5075'),
('2','3-D Animations in Cinematic Arts Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6089'),
('3','3-D Art for Games Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5077'),
('4','3-Dimensional Design Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5076'),
('5','3D Computer Graphics and Modeling','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6127'),
('6','Accounting Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5150'),
('7','Advertising Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5473'),
('8','American Popular Culture Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5194'),
('9','American Studies and Ethnicity Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5193'),
('10','Animation and Digital Arts Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5175'),
('11','Applied Analytics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6070'),
('12','Applied Computer Security Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5637'),
('13','Applied Theatre Arts Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5513'),
('14','Arabic and Middle East Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5347'),
('15','Arabic Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6088'),
('16','Architecture Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5052'),
('17','Art History Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5209'),
('18','Astronautical Engineering Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5552'),
('19','Astronomy Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5394'),
('20','Behavioral Economics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6090'),
('21','Biotechnology Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5220'),
('22','Business Economics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5093'),
('23','Business Finance Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5094'),
('24','Business Law Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5095'),
('25','Business Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5092'),
('26','Business Technology Fusion Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5096'),
('27','Ceramics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5067'), 
('28','Chemistry Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5238'), 
('29','Cinema-Television for the Health Professions Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5723'), 
('30','Cinematic Arts Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5176'),
('31','Classical Perspectives Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6107'),
('32','Classics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5243'),
('33','Comedy (Performance) Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5514'), 
('34','Comedy Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5177'), 
('35','Communication Design Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5068'), 
('36','Communication Policy and Law Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6091'), 
('37','Communication Technology Practices and Platforms Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5452'), 
('38','Comparative Literature Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5247'), 
('39','Computational Biology and Bioinformatics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5221'), 
('40','Computer and Digital Forensics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5638'), 
('41','Computer Programming Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5639'), 
('42','Computer Science Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5600'), 
('43','Construction Planning and Management Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5586'), 
('44','Construction Planning and Management Minor (Public Policy)','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5900'), 
('45','Consumer Behavior Interdisciplinary Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5414'), 
('46','Consumer Behavior Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5097'),
('47','Craniofacial and Dental Technology Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5484'), 
('48','Critical Approaches to Leadership Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5327'),
('49','Cultural Anthropology Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5200'), 
('50','Cultural Competence in Medicine Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5724'), 
('51','Cultural Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5289'),
('52','Culture, Media and Entertainment Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5450'), 
('53','Cultures and Politics of the Pacific Rim Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5271'), 
('54','Dance in Popular Culture: Hip-Hop, Urban and Social Dance Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5481'), 
('55','Dance Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5482'), 
('56','Digital Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5178'), 
('57','Drawing Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5070'), 
('58','Early Modern Studies Interdisciplinary Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5290'), 
('59','Earth Sciences Minor: Climate Change, Stewardship and Resiliency','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5913'), 
('60','East Asian Area Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5264'), 
('61','East Asian Languages and Cultures Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5270'), 
('62','Economics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5278'), 
('63','Education and Society Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5520'), 
('64','Engineering Management Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5626'), 
('65','English Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5287'), 
('66','Enterprise Information Systems Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5640'), 
('67','Entertainment Industry Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5179'), 
('68','Entrepreneurship Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5098'), 
('69','Environmental Chemistry and Sustainability Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5239'), 
('70','Environmental Engineering Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5593'), 
('71','Environmental Health Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5725'), 
('72','Environmental Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5305'), 
('73','Ethics and Moral Philosophy Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5378'), 
('74','Folklore and Popular Culture Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5201'),
('75','Forensics and Criminality Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5433'), 
('76','French Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5309'), 
('77','Game Animation Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5180'), 
('78','Game Audio Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5181'), 
('79','Game Design Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5182'), 
('80','Game Entrepreneurism Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5183'), 
('81','Game Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5184'), 
('82','Game User Research Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5185'), 
('83','Gender and Social Justice Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6099'), 
('84','Gender Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5313'), 
('85','Geobiology Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5259'), 
('86','Geohazards Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5260'), 
('87','German Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5316'),
('88','Global Communication Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5333'), 
('89','Global Health Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5726'), 
('90','Health Administration Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5823'), 
('91','Health Care Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5713'), 
('92','Health Communication Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5727'), 
('93','Health Policy Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5824'), 
('94','History and Culture of Business Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5323'), 
('95','History Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5322'), 
('96','Human Movement Sciences Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5915'),
('97','Human Resource Management Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5099'), 
('98','Human Rights Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5401'), 
('99','Human Security and Geospatial Intelligence Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6137'), 
('100','Individuals, Societies and Aging Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5658'), 
('101','Innovation: The Digital Entrepreneur Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5100'), 
('102','Interdisciplinary Archaeology Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5422'), 
('103','International Health, Development, and Social Justice Interdisciplinary Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5328'), 
('104','International Policy and Management Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5334'), 
('105','International Relations Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5332'), 
('106','Iranian Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5368'), 
('107','Italian Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5311'), 
('108','Jazz Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5758'), 
('109','Jewish American Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5195'), 
('110','Jewish Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6100'), 
('111','Judaic Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5338'), 
('112','Korean Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5265'), 
('113','Landscape Architecture Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5053'), 
('114','Latin American Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5440'), 
('115','Law and Public Policy Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5825'), 
('116','Law and Society Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5402'), 
('117','LGBTQ Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5314'), 
('118','Linguistics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5346'), 
('119','Luso-Brazilian Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6101'), 
('120','Management Consulting Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5101'),  
('121','Managing Human Relations Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5434'), 
('122','Marketing Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5102'), 
('123','Mathematical Finance Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5352'), 
('124','Mathematics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5358'), 
('125','Media and Social Change Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5186'), 
('126','Media Economics and Entrepreneurship Interdisciplinary Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5922'), 
('127','Media Economics and Entrepreneurship Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5111'), 
('128','Medical Anthropology Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5202'),
('129','Middle East Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5369'), 
('130','Mobile App Development Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5641'), 
('131','Music Industry Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5757'), 
('132','Music Production Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5910'),  
('133','Music Recording Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5756'), 
('134','Musical Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5760'), 
('135','Musical Theatre Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5759'), 
('136','Nanotechnology Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6116'), 
('137','Narrative Structure Interdisciplinary Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5291'), 
('138','Natural Science Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5222'), 
('139','Neuroscience Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5373'), 
('140','News Media and Society Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5474'), 
('141','Nonprofits, Philanthropy and Volunteerism Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5826'), 
('142','Nutrition and Health Promotion Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5729'), 
('143','Occupational Science Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5679'), 
('144','Operations and Supply Chain Management Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5103'), 
('145','Organizational Leadership and Management Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5104'), 
('146','Painting Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5071'),  
('147','Performance Science Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6102'), 
('148','Performing Arts Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5515'), 
('149','Petroleum Engineering Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5574'),  
('150','Philosophy Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5379'), 
('151','Photography and Social Change Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5435'), 
('152','Photography Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5072'), 
('153','Physics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5393'), 
('154','Playwriting Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5516'), 
('155','Political Organizing in the Digital Age Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5404'), 
('156','Political Science Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5400'), 
('157','Popular Music Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5761'), 
('158','Professional and Managerial Communication Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5453'),  
('159','Psychology and Law Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5413'), 
('160','Psychology Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5412'), 
('161','Public Health Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5728'), 
('162','Public Relations Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6092'), 
('163','Race, Ethnicity and Politics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5403'), 
('164','Real Estate Development Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5827'),
('165','Real Estate Finance Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5105'), 
('166','Religion Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5423'),
('167','Resistance to Genocide Interdisciplinary Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5321'), 
('168','Russian Area Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5428'), 
('169','Russian Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5427'), 
('170','Science and Management of Biomedical Therapeutics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6103'),
('171','Science Visualization Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5187'), 
('172','Science, Health and Aging Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5659'), 
('173','Science, Technology, and Society Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5436'), 
('174','Screenwriting Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5188'), 
('175','Sculpture Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5073'),
('176','Social Entrepreneurship Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5106'), 
('177','Sociology Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5432'),
('178','Songwriting Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5762'), 
('179','Southeast Asia and its People Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5203'), 
('180','Spanish Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5439'), 
('181','Spatial Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5442'),
('182','Sports Media Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5454'), 
('183','Statistics Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5357'), 
('184','Substance Abuse Prevention Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5730'), 
('185','Teaching English to Speakers of Other Languages (TESOL) Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5521'), 
('186','Technology Commercialization Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5107'), 
('187','The Dynamics of Early Childhood Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5905'), 
('188','Theatre Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5517'), 
('189','Thematic Approaches to Humanities and Society Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5448'), 
('190','Themed Entertainment Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6108'), 
('191','Theories of Art Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5380'), 
('192','Two-Dimensional Studies Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5074'), 
('193','Urban Sustainable Planning Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=6094'), 
('194','Video Game Design and Management Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5642'), 
('195','Video Game Programming Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5643'), 
('196','Visual Culture Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5210'), 
('197','Web Technologies and Applications Minor','http://catalogue.usc.edu/preview_program.php?catoid=6&poid=5644');


/*CREATE GRADYEAR TABLE */
CREATE TABLE GradYear (
	GradYID INT(11) PRIMARY KEY AUTO_INCREMENT,
    year int(11) NOT NULL
);
/*INSERT GRADYEARS */
INSERT INTO GradYear
VALUES('1','2019'),
('2','2020'),
('3','2021'),
('4','2022'),
('5','2023'),
('6','2024'),
('7','2025'),
('8','2026'),
('9','2027'),
('10','2028');

/*CREATE SCHEDULE TABLE - TODO */

/*CREATE USER TABLE */
CREATE TABLE User (
	UserID INT(11) PRIMARY KEY AUTO_INCREMENT,
    userName VARCHAR(30) NOT NULL,
    pass VARCHAR(30) NOT NULL,
	majorID INT(11) NOT NULL,
    minorID INT(11) NOT NULL,
    gradYID INT(11) NOT NULL,
    FOREIGN KEY fk1 (majorID) REFERENCES Major(MajorID),
    FOREIGN KEY fk2 (minorID) REFERENCES Minor(MinorID),
    FOREIGN KEY fk3 (gradYID) REFERENCES GradYear(GradYID)
    );


/*CREATE FOLLOW TABLE */
CREATE TABLE Follow (
	FollowID INT(11) PRIMARY KEY AUTO_INCREMENT,
    user1ID INT(11) NOT NULL,
    user2ID INT(11) NOT NULL,
    FOREIGN KEY fr1 (user1ID) REFERENCES User(UserID),
    FOREIGN KEY fr2 (user2ID) REFERENCES User(UserID)
);


/*CREATE UPDATE TABLE */
CREATE TABLE Updates (
	UpdateID INT(11) PRIMARY KEY AUTO_INCREMENT,
    userID INT(11) NOT NULL,
    content VARCHAR(1000),
    FOREIGN KEY fu1 (userID) REFERENCES User(UserID)
);


/*CREATE PREVIOUSCLASS TABLE */
CREATE TABLE PreviousClass (
	PrevCID INT(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(300),
    userID INT(11) NOT NULL,
    FOREIGN KEY fp1 (userID) REFERENCES User(UserID)
);


/*CREATE CURRENTCLASS TABLE */
CREATE TABLE CurrentClass (
	CurrCID INT(11) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(300),
    type VARCHAR(30),
    section VARCHAR(30),
    location VARCHAR(30),
    startTime VARCHAR(30),
    endTime VARCHAR(30),
    days VARCHAR(30),
    professor VARCHAR(30),
    userID INT(11) NOT NULL,
    FOREIGN KEY fc1 (userID) REFERENCES User(UserID)
);

CREATE TABLE SchedulSlot (
	SlotID INT(11) PRIMARY KEY AUTO_INCREMENT,
	startTime VARCHAR(30),
	endTime VARCHAR(30),
	Monday VARCHAR(100),
	Tuesday VARCHAR(100),
	Wednesday VARCHAR(100),
	Thursday VARCHAR(100),
	Friday VARCHAR(100),
	UserID INT(11) NOT NULL,
	FOREIGN KEY fl1 (userID) REFERENCES User(UserID)
);

